# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-30 18:27
from __future__ import unicode_literals

from django.db import migrations

import markdownx


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180130_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='md_body',
            field=markdownx.models.MarkdownxField(default='', verbose_name='MD内容'),
        ),
    ]
